FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

WORKDIR /app

ARG BUILD_ENV=local
ENV BUILD_ENV=${BUILD_ENV}

RUN apt-get update && \
    apt-get install -y poppler-utils \
    python3.10-dev \
    build-essential \
    python3-pip \
    ffmpeg \
    redis-server

RUN pip install uv

COPY . /app/

# Copy entrypoint script and set permissions
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN uv sync
RUN uv pip install flash-attn==2.7.4.post1 --no-build-isolation

ENV PYTHONBUFFERED=1

ENTRYPOINT ["/app/entrypoint.sh"]
