FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

WORKDIR /app

ARG BUILD_ENV=local
ENV BUILD_ENV=${BUILD_ENV}

RUN apt-get update && \
    apt-get install -y poppler-utils \
    python3-pip \
    redis-server \
    git && rm -rf /var/lib/apt/lists/*

RUN pip install uv
RUN git clone https://github.com/ai-forever/Kandinsky-5.git /tmp/kandinsky && \
    mv /tmp/kandinsky/kandinsky /app/kandinsky && \
    rm -rf /tmp/kandinsky

COPY . /app/

RUN uv sync
RUN uv run python kandinsky/download_models.py


COPY entrypoint.sh /app/entrypoint.sh
COPY install_sage_attention.sh /app/install_sage_attention.sh
RUN chmod +x /app/entrypoint.sh /app/install_sage_attention.sh

ENV PYTHONBUFFERED=1

ENTRYPOINT ["/app/entrypoint.sh"]
