FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

ARG BUILD_ENV=local
ENV BUILD_ENV=${BUILD_ENV}

# Install Python, pip, git, and other essentials
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
    python3.10 python3-pip git ffmpeg redis-server \
    && rm -rf /var/lib/apt/lists/*

# Set python3.10 as the default python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

WORKDIR /app

# Install 'uv' for faster package management
RUN pip install uv

ENV TORCH_CUDA_ARCH_LIST="8.0;8.6;8.9;9.0+PTX"

# Copy project files
COPY pyproject.toml .
# Install Python dependencies using uv
RUN uv sync

COPY . .
# Make the model's code importable by adding it to the PYTHONPATH
# Clone the model's repository
RUN git clone https://github.com/facebookresearch/sam2.git && \
    cd sam2 && \
    git checkout 0e78a118995e66bb27d78518c4bd9a3e95b4e266 && \
    uv pip install -e .
ENV SAM2_REPO_ROOT="/app/sam2"
ENV PYTHONPATH="${SAM2_REPO_ROOT}:${PYTHONPATH}"
RUN git clone https://github.com/Wan-Video/Wan2.2.git
ENV PYTHONBUFFERED=1
ENV PYTHONPATH="${PYTHONPATH}:/app/Wan2.2"

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

ENV PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]