FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

# Prevent interactive prompts during build
ENV DEBIAN_FRONTEND=noninteractive

ARG BUILD_ENV=local
ENV BUILD_ENV=${BUILD_ENV}

# Install Python, pip, git, and other essentials
RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
    python3.10 python3-pip git ffmpeg redis-server libcairo2-dev pkg-config curl\
    && rm -rf /var/lib/apt/lists/*

# Set python3.10 as the default python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

WORKDIR /app

RUN pip install uv

ENV TORCH_CUDA_ARCH_LIST="8.0;8.6;8.9;9.0+PTX"

RUN uv venv
COPY pyproject.toml /app/pyproject.toml
RUN uv sync

# --- APPLICATION SETUP STAGE ---
# Now we clone repos and copy application code. Any changes here will only affect
# subsequent steps, not the dependency installation above.

# Clone ComfyUI repo
RUN mkdir comfyui_logic
RUN cd /app/comfyui_logic && git clone https://github.com/comfyanonymous/ComfyUI.git
# Install all custom nodes
RUN cd /app/comfyui_logic/ComfyUI/custom_nodes && \
    git clone https://github.com/evanspearman/ComfyMath.git && \
    git clone https://github.com/Fannovel16/comfyui_controlnet_aux.git && \
    git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git && \
    git clone https://github.com/yolain/ComfyUI-Easy-Use.git && \
    git clone https://github.com/Fannovel16/ComfyUI-Frame-Interpolation.git && \
    git clone https://github.com/kijai/ComfyUI-KJNodes.git && \
    git clone https://github.com/MixLabPro/comfyui-mixlab-nodes.git && \
    git clone https://github.com/kijai/ComfyUI-segment-anything-2.git && \
    git clone https://github.com/un-seen/comfyui-tensorops.git && \
    git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git && \
    git clone https://github.com/kijai/ComfyUI-WanVideoWrapper.git && \
    git clone https://github.com/rgthree/rgthree-comfy.git

# Copy all application-specific files in one go.
# If any of these files change, only this layer and subsequent ones are rebuilt.
COPY comfyui_logic/workflow.py /app/comfyui_logic/workflow.py
COPY celery_worker.py .
COPY entrypoint.sh .

ENV PYTHONBUFFERED=1

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]