steps:
  # Setup buildx for multi-platform builds
  - name: "gcr.io/cloud-builders/docker"
    args: ["buildx", "create", "--name", "multiplatform", "--use"]

  # Login to Docker Hub
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker login -u $$DOCKER_USERNAME -p $$DOCKER_PASSWORD"
    secretEnv: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]

# Build wan-animate-server image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG="${TAG_NAME#wan-animate-}"
        docker buildx build \
          --platform=linux/amd64 \
          --tag=elliotcarery/wan-animate-server:$$TAG \
          --push \
          -f dockerfile \
          .
    env:
      - 'TAG_NAME=$TAG_NAME'
    dir: 'wan-animate'

# Configure secrets
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-username/versions/latest
      env: "DOCKER_USERNAME"
    - versionName: projects/$PROJECT_ID/secrets/docker-password/versions/latest
      env: "DOCKER_PASSWORD"

options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/caramel-duality-382403/serviceAccounts/techlistpair@caramel-duality-382403.iam.gserviceaccount.com"
