[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "torch==2.8.0",
    "torchaudio==2.8.0",
    "celery",
    "whisperx==3.7.4",
    "python-magic",
]

extra-index-url = [
    "https://download.pytorch.org/whl/cu128",
]

[tool.setuptools]
packages = ["subtitles_generator"]